image: vauxoo/odoo-80-image-shippable-auto
stages:
  - main
  - build

lint:
  stage: main
  tags:
    - lint
  variables:
    LINT_CHECK: "1"
    TESTS: "0"
  script:
    - source variables.sh
    - git clone --depth=1 https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - pip3 install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools check_keys
    - export TRAVIS_PYTHON_VERSION="3.6"  # Lint job is not compatible with neither py3.8 nor 3.7 but 3.6
    - source ${REPO_REQUIREMENTS}/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate
    - source ${REPO_REQUIREMENTS}/virtualenv/nodejs/bin/activate
    - source /usr/local/rvm/scripts/rvm
    - travis_install_nightly
    - travis_run_tests

odoo:
  stage: main
  coverage: '/^TOTAL.*\s+(\d+(?:\.\d+)\%)$/'
  tags:
    - odoo
    - test
  variables:
    LINT_CHECK: "0"
    TESTS: "1"
    STDOUT_LOG: "./${CI_COMMIT_REF_SLUG}/odoo.log"
  script:
    - source variables.sh
    - git clone --depth=1 https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - pip3 install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools check_keys
    - export TRAVIS_PYTHON_VERSION="3.7"  # CI docker image is not compatible with py3.8 but py3.7
    - source ${REPO_REQUIREMENTS}/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate
    - source ${REPO_REQUIREMENTS}/virtualenv/nodejs/bin/activate
    - source /usr/local/rvm/scripts/rvm
    - travis_install_nightly
    - travis_run_tests
    - travis_after_tests_success || true
    - coverage html --rcfile=${CI_PROJECT_DIR}/.coveragerc -d $CI_COMMIT_REF_SLUG || true
    - coverage xml --rcfile=${CI_PROJECT_DIR}/.coveragerc -o $CI_COMMIT_REF_SLUG/coverage.xml || true
    - coverage report -m --show-missing --rcfile=${CI_PROJECT_DIR}/.coveragerc || [[ $? != 2 ]]
  artifacts:
    paths:
      - $CI_COMMIT_REF_SLUG
    reports:
      cobertura: $CI_COMMIT_REF_SLUG/coverage.xml

publish_coverage:
  image: quay.io/vauxoo/dockerv
  stage: build
  allow_failure: true
  dependencies:
    - odoo
  script:
    - deployvcmd gitlab_tools push_coverage
  environment:
    name: coverage
    url: https://coverage.vauxoo.com/${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}

odoo_warnings:
  image: quay.io/vauxoo/dockerv:latest
  stage: build
  allow_failure: true
  dependencies:
    - odoo
  script:
    - deployvcmd gitlab_tools check_log --logpath="./$CI_COMMIT_REF_SLUG"
